### ISSUE TITLE
Reposicionamento de elementos bloqueado

### ISSUE THREAD

**Issue by liviasmarques** [miltonbsn/brmodelo#197]
**Describe the bug**
Só é possível mover os elementos uma vez no modelo lógico

**Steps to reproduce**
1. Crie modelo conceitual
2. Gere modelo lógico do modelo conceitual criado
3. Reposicione algum elemento
4. Tente reposicionar outro elemento

**Expected behavior**
Possibilidade de reposicionar todos os elementos do modelo

**Softwares version (please complete the following information):**
 - OS: windows
 - Browser: Chrome 93.0.4577.82 

**Additional context**
É possível fazer uma cópia do modelo lógico e, nessa cópia, consigo mover elementos, mas no original não

**Comment by miltonbsn** [comment]
Oi @liviasmarques, obrigado por reportar esse problema.

Você pode passa a url da sua modelo (o link lá do browser mesmo)? Pelo Id eu vou buscar a sua modelagem e ver se ela tem algum problema. Eu testei aqui e parece estar ok, pode ser algum erro gerado na sua conversão que tá travando a tela.

Aguardo o link e aí já confiro pra você

**Comment by miltonbsn** [comment]
@liviasmarques Tem algum update ? Voltou a funcionar? Se não, poderia me passar a url da modelagem que está acontecendo?

**Comment by liviasmarques** [comment]
Oi, @miltonbsn! Gerei outro aqui para testar e continua acontecendo: https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%22614e4d3ffcef0700339fdcc7%22,%22conversionId%22:%226147a16af7313400333f1c78%22%7D

O modelo conceitual do qual gerei é esse: https://app.brmodeloweb.com/#!/conceptual/6147a16af7313400333f1c78

**Comment by miltonbsn** [comment]
@liviasmarques, consegui descobrir o problema. O relacionamento "execução" não estava bem conectado com a tabela "chamados" no seu modelo conceitual original. Por isso a conversão falhava e a tela travava.

![image](https://user-images.githubusercontent.com/881231/135322121-dcf2ceb0-19ac-41b5-be45-a5b223d785a4.png)

Corrigi as conexões do seu modelo e logo vou lançar uma nova versão que impossibilite que a linha não conecte no elemento e também valide antes de começar uma nova conversão.

Se você converter novamente agora deve dar certo. Qualquer outro problema é só abrir uma issue aqui que a gente corrige. 

Se puder deixar uma estrela aqui no git do projeto ajuda bastante a gente continuar trabalhando na brmodeloweb :)

**Comment by miltonbsn** [comment]
@liviasmarques pode conferir? A gente pode fechar a issue?

**Comment by liviasmarques** [comment]
@miltonbsn funcionou sim!! Obrigada e parabéns pelo projeto (:
