### ISSUE TITLE
Erro ao clicar em editar um Relacionamento

### ISSUE THREAD

**Issue by gzmael** [miltonbsn/brmodelo#198]
**Describe the bug**
Ao criar um relacionamento e ligar com a linha, não é possível editar as cardinalidades apertando no botão da engrenagem. Aparece o erro: "Cannot read properties of undefined (reading 'attributes')"

**Steps to reproduce**
1. Adicionar duas Entidade
2. Adicionar um Relacionamento
3. Puxar uma linha do Relacionamento para a Entidade
4. Tentar editar as cardinalidades com o botão de engrenagem

**Expected behavior**
Deveria ser possível a edição das cardinalidades

**Screenshots**
![Captura de tela de 2021-09-24 09-47-42](https://user-images.githubusercontent.com/896631/134676658-260ba6f7-526a-4550-bbd2-ca50c178d173.png)

**Softwares version (please complete the following information):**
 - OS: Linux Mint
 - Browser: Google Chrome Versão 94.0.4606.54

**Comment by miltonbsn** [comment]
Olá @gzmael, obrigado por reportar. Eu homologuei seguindo os passos que você descreveu e não consegui reproduzir

![image](https://user-images.githubusercontent.com/881231/134694494-aee09bfe-2a3f-43c2-9028-8b1caceb7703.png)

Tenta fazer o seguinte: 

1) remove esses elementos
2) salva
3) recarrega a pagina (ou cria uma modelagem nova)
4) Puxa duas novas entidades para tela
5) liga elas (sem o relacionamento), isso deveria criar uma relacionamento entre elas
6) clica na engrenagem e vê se da certo

Me conta se vai, se não ser vou carregar aqui sua modelagem aqui pra ver se descubro algo

**Comment by gzmael** [comment]
> Olá @gzmael, obrigado por reportar. Eu homologuei seguindo os passos que você descreveu e não consegui reproduzir
> 
> ![image](https://user-images.githubusercontent.com/881231/134694494-aee09bfe-2a3f-43c2-9028-8b1caceb7703.png)
> 
> Tenta fazer o seguinte:
> 
> 1. remove esses elementos
> 2. salva
> 3. recarrega a pagina (ou cria uma modelagem nova)
> 4. Puxa duas novas entidades para tela
> 5. liga elas (sem o relacionamento), isso deveria criar uma relacionamento entre elas
> 6. clica na engrenagem e vê se da certo
> 
> Me conta se vai, se não ser vou carregar aqui sua modelagem aqui pra ver se descubro algo

Ainda apresenta o mesmo problema. Não consegue editar os relacionamentos. Como é mostrado no vídeo abaixo.
https://user-images.githubusercontent.com/896631/134910274-13729a2f-1445-4b6e-89af-d91b4ac51203.mp4

Também segui os mesmos passos no Firefox 92.0 e nele aparece um outro erro no console.
![Captura de tela de 2021-09-27 09-45-17](https://user-images.githubusercontent.com/896631/134910636-be15dba5-0ea7-4c17-8a33-effb78db1e09.png)

**Comment by miltonbsn** [comment]
@gzmael consegui reproduzir o primeiro problema que você reportou. Ao puxar uma linha até um elemento e não alcançar, ou seja, soltar a linha em uma área branca de edição, ocasiona um erro e a tela trava mesmo.

![image](https://user-images.githubusercontent.com/881231/134947067-6f4260ef-ab62-463b-8e13-52b9a8d0ad9f.png)

Obrigado pro reportar isso, logo vou lançar uma versão corrigindo o comportamento.

Agora vendo o seu vídeo, acho que esse segundo ponto é só usabilidade mesmo, você precisa que abrir o menu de edição no ícone "<<"

https://user-images.githubusercontent.com/881231/134948112-d4289301-239b-4d7d-a18c-dd2aefcf8bf2.mp4

**Comment by miltonbsn** [comment]
@gzmael conseguiu? A gente pode fechar a issue?

**Comment by gzmael** [comment]
> @gzmael conseguiu? A gente pode fechar a issue?

Consegui sim, da forma que você explicou. Pode fechar a issue 👍🏽
