### ISSUE TITLE
Seleção dos elementos

### ISSUE THREAD

**Issue by gutobr9** [miltonbsn/brmodelo#208]
Ao selecionar todos os elementos, pressionando SHIFT e passando o mouse em cima, ele seleciona todos os elementos e consigo mover. No entanto, ao clicar fora, ou ESC a seleção ainda continua.
Entendo que ao clicar fora, deveria liberar a seleção dos elementos.

**Comment by idmarjr** [comment]
Estamos revendo alguns comportamentos padrão do canvas e adicionando mais atalhos de teclado.
Esses comportamentos problemáticos vão ser resolvidos como _side effect_ do #248
