### ISSUE TITLE
Atalhos

### ISSUE THREAD

**Issue by gutobr9** [miltonbsn/brmodelo#209]
Poderia ser implementado atalhos, como:
Del = deletar o objeto selecionado
Ctrl+Z = Desfazer
Ctrl+Y = Refazer
SHIFT+"+" = Zoom In
SHIFT+"-" = Zoom Out
SHIFT+E = Entidade
SHIFT+R = Relacionamento
SHIFT+D = Duplicar
SHIFT+L = Modelo Lógico
.
.
.

**Comment by idmarjr** [comment]
Oi @gutobr9 !

Muito obrigado pela sugestão.
Alguns desses atalhos já estão na fila pra serem implementados como por exemplo desfazer/refazer: https://github.com/brmodeloweb/brmodelo-app/issues/77

O comportamento do zoom também deve sofrer alterações em breve e junto com essas mudanças os atalhos vão ser adicionados.

---

Vou manter essa _issue_ aberta e usar ela como base pra criar _issues_ individuais pra cada contexto de atalho ao longo das próximas semanas.

---

Se você se sentir confiante pra implementar qualquer um desses atalhos, _pull requests_ são mais do que bem vindos! :)

**Comment by idmarjr** [comment]
@gutobr9 Nem todas as suas sugestões de atalhos vão ser adicionadas ou seguir a combinação de teclas que você sugeriu. Mas estamos trabalhando pra melhorar os atalhos de teclado no #248
