### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Smiriflores** [miltonbsn/brmodelo#211]
estou ultilizando o programa e não estou conseguindo trocar o nome da entidade nem colocar os atributos

**Comment by idmarjr** [comment]
Oi @Smiriflores !

Você pode por favor nos fornecer algumas informaçõesextras?

- Link da modelagem com a qual você está tendo o problema
   Algo como: `https://app.brmodeloweb.com/#!/conceptual/6174732e95cd9e003483fa94`
- Qual o browser e a versão que você está usando

Além disso, se for possível, por favor tenta criar uma modelagem nova e vê se você enfrenta o mesmo problema ou se isso tá acontecendo com uma modelagem específica.
