### ISSUE TITLE
Não permite excluir a linha de atributo que foi adicionada

### ISSUE THREAD

**Issue by brunomikaelalencar** [miltonbsn/brmodelo#283]
**Describe the bug**

**Steps to reproduce**
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Softwares version (please complete the following information):**
 - OS: [e.g. iOS10]
 - Browser: [e.g. Firefox 79.0, Opera 69.2]

**Additional context**

**Comment by idmarjr** [comment]
Oi @BrunoMikaelAlencarDePanha 

Teria como você nos dar mais detalhes sobre esse problema?

- Qual tipo de modelagem você está criando? Conceitual ou lógica?
- Qual navegador você está usando (E qual a versão)
- Qual a URL da modelagem que você está encontrando esse problema?

Se for possível, você pode compartilhar um screenshot ou um video do problema?

**Comment by idmarjr** [comment]
Estou fechando essa _issue_ por falta de informação pra que possamos identificar e corrigir o problema
Lembrando que sempre podemos reabri-la se necessário. :)
