### ISSUE TITLE
I need help with: Deleting my account

### ISSUE THREAD

**Issue by felipgab** [miltonbsn/brmodelo#312]
I want to delete my account (felipegabriel1110[at]gmail).

**Comment by idmarjr** [comment]
Hi @felipgab 

First of all, I'm sorry we don't allow you to delete your account on your own yet.
We're working to add this option to BR Modelo Web in early 2022.


> That said, I just want to confirm you're aware this is a destructive action. You will not be able to recover your account or  any data after we delete it so please make sure to backup any data you want to keep safe.

Can you please answer here confirming you're aware of this and really want to delete your account?
Once I have this answer I will proceed deleting it.

**Comment by felipgab** [comment]
Yes, I confirm. Thank you and have a nice day ;)

**Comment by miltonbsn** [comment]
@idmarjr @felipgab done
