### ISSUE TITLE
DONT GENERATE TO SQL

### ISSUE THREAD

**Issue by RodriguesRd** [miltonbsn/brmodelo#313]
**Describe the bug**
after to made the model I press the button generate sql but nothing happened

**Steps to reproduce**
1. Go to 'create tables 
2. Click on 'salve '
3.Click the button generate sql

**Softwares version (please complete the following information):**
 - OS: [Windows10]
 - Browser: [Google crhome  version 96.0.4664.110]

**Additional context**

**Comment by idmarjr** [comment]
Oi @RodriguesRd !
Você pode nos dar mais detalhes do problema?

Se for possível, cola aqui pra gente a URL do modelo que você está tendo o problema.

**Comment by idmarjr** [comment]
Como já se passaram 23 dias e não tivemos resposta, estou fechando essa issue.
Lembrando que sempre podemos reabri-la se necessário.
