### ISSUE TITLE
Não está salvando as alterações

### ISSUE THREAD

**Issue by ramoti** [miltonbsn/brmodelo#317]
Crio uma tabela, clico em salvar e não aparece "salvo com sucesso"

Clico ctrl + s, aparece salvo com sucesso, quando sou f5 ele não salvou, como corrigir isso?

**Comment by ramoti** [comment]
Parece ser uma inconsistência, as vezes salva as vezes não

**Comment by idmarjr** [comment]
Vou fechar essa issue pra que a gente possa concentrar a discussão na #318
