### ISSUE TITLE
it's ok

### ISSUE THREAD

**Issue by IsabelaShimizu** [miltonbsn/brmodelo#322]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context?**

**Comment by idmarjr** [comment]
Oi @IsabelaShimizu 

Vi que tu abriu a issue mas acabou não descrevendo detalhes da feature.

Se tiver algo que a gente possa ajudar fica a vontade pra reabrir o ticket ok?
