### ISSUE TITLE
Não consigo clicar em nada

### ISSUE THREAD

**Issue by arthurjolo** [miltonbsn/brmodelo#329]
O progama não deixa eu selecionar nenhum objeto nem adicionar ou mover

**Comment by scrNorya** [comment]
O mesmo ocorreu aqui

SO: Windows 10 Pro - 10.0.19044
Navegador: Google Chrome - 98.0.4758.102
URL da modelagem: https://app.brmodeloweb.com/#!/conceptual/621575f6c8ef2ab3d7a0b96b

Acredito que tenha relação com desfazer (ctrl z)
Quando ocorreu, a maioria das ligações desapareceram e ficou esse comportamento descrito pelo @arthurjolo 
Mesmo depois de salvar, fechar e abrir novamente o comportamento continua nessa modelagem

<Details>
<Summary>Vídeo</Summary>

https://user-images.githubusercontent.com/45461780/155634251-8e066b7c-6f98-40a1-89be-9fe667506ec3.mp4
</Details>

Aliás parece que quando abri a URL em um navegador anônimo a modelagem voltou a funcionar normalmente (com todas as alterações feitas que não ficaram visíveis antes)

**Comment by miltonbsn** [comment]
Olá @scrNorya @arthurjolo, obrigado por reportar o problema!

Quando isso acontece geralmente é por causa de uma ação que gerou um erro e o programa não tratou, aí o editor congela e tudo que você tentar fazer dai em diante não vai funcionar. Eu vou investigar o ctrl z e tentar ver se acho algo nas suas modelagens. @arthurjolo se puder me passar o link da sua para eu dar uma olhada.

Se isso acontecer, eu sugiro tentar observar a ultima ação antes do problema começar e mandar aqui pra gente, assim eu consigo identificar a causa e aplicar uma correção para todos. Se a modelagem tiver corrompido e você salvou, não vai ser mais possível seguir com ela, o editor vai ficar sempre congelado até que eu corrija no banco. Se tiver começando é melhor excluir essa e começar uma nova, se ela já estiver mais avançada vocês podem mandar aqui que eu tento corrigi-la, mas sempre que conseguirem identificar o que causou reportem que a gente arruma a causa.

Obrigado e abraços ;)

**Comment by idmarjr** [comment]
Vou fechar essa _issue_ porque ela está inativa a algum tempo.  
Se o problema acontecer novamente é só comentar aqui novamente e reabrimos o ticket. :)
