### ISSUE TITLE
Ctrl + C  Ctrl + V

### ISSUE THREAD

**Issue by JuliaGomesDev** [miltonbsn/brmodelo#332]
Gostaria de sugerir que durante a modelagem pemitissem o recurso de Ctrl + C  Ctrl + V de um objeto ou tabela. Facilitaria muito para quando é necessário criar-se entidades semelhantes.

**Comment by idmarjr** [comment]
Oi @JuliaGomesDev !  
Muito obrigado pela sugestão. :) 

Copiar e colar está no nosso radar de _features_ pra serem implementadas mas por hora não temos uma previsão de quando isso vai acontecer. 😓

Vou deixar essa issue aberta e quando essa funcionalidade for pro ar, volto aqui pra te avisar!
