### ISSUE TITLE
Modelagem lógica

### ISSUE THREAD

**Issue by klialves** [miltonbsn/brmodelo#333]
O site não está convertendo o modelo conceitual para o lógico, mas criando um documento totalmente em branco.

**Comment by idmarjr** [comment]
Oi @klialves !
Esse problema está acontecendo com modelagens diferentes?

Você pode por favor colar a URL das modelagens que estão apresentando esse problema pra que a gente possa investigar mais a fundo?

**Comment by klialves** [comment]
Está acontecendo com todas as modelagens, tentei até pelo celular e ficou
do mesmo jeito, não gera a modelagem lógica, só cria um arquivo novo com o
nome do arquivo da modelagem conceitual, aí tenho que fazer tudo
manualmente do zero

Em sáb, 9 de abr de 2022 21:16, Idmar Ramos Jr. (Id) <
***@***.***> escreveu:

**Comment by klialves** [comment]
A modelagem em questão é essa:
https://app.brmodeloweb.com/#!/conceptual/6248bc6b092517a61906c506

Em sáb, 9 de abr de 2022 21:53, Klí Winters ***@***.***>
escreveu:

**Comment by miltonbsn** [comment]
Oi @klialves, corrigi seu modelo.

Haviam algumas conexões que não estavam bem "encaixadas". Algumas chaves não estavam bem conectadas às entidades e havia também um relacionamento mal conectado.

Em breve vou melhorar as validações pra deixar isso mais evidente, mas por agora você já pode converter o seu modelo :)
 
Obrigado por reportar e se precisar estamos aqui. Ah, se você ainda não deixou uma estrelinha aqui no git, isso ajuda bastante a gente a continuar mantendo o projeto
