### ISSUE TITLE
um botão em cima do outro

### ISSUE THREAD

**Issue by joaoneivaneto** [miltonbsn/brmodelo#338]
quando é necessário salvar uma coluna da tabela na modelagem lógica, o botão depara relatar bug fica em cima do botão de salvar

**Comment by idmarjr** [comment]
Oi @joaoneivaneto 
Vou investigar esse bug. Você pode por favor me dar mais duas infos pra facilitar o trabalho?

1. Link da modelagem na qual você está encontrando esse problema
1. Um screenshot a tela com o problema acontecendo

Obrigado!

**Comment by joaoneivaneto** [comment]
brModeloWeb

Se você perceber aqui no canto inferior direito var perceber o problema

Enviado do Email para Windows De: Idmar Ramos Jr. (Id)Enviado:quinta-feira, 28 de abril de 2022 10:32Para: brmodeloweb/brmodelo-appCc:joaoneivaneto; MentionAssunto: Re: [brmodeloweb/brmodelo-app] um botão em cima do outro (Issue #338) Oi @joaoneivanetoVou investigar esse bug. Você pode por favor me dar mais duas infos pra facilitar o trabalho?Link da modelagem na qual você está encontrando esse problemaUm screenshot a tela com o problema acontecendoObrigado!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by idmarjr** [comment]
@joaoneivaneto acho que rolou algum problema no seu cliente de email.  
Sua mensagem veio como texto cru e sem a imagem anexa :(

**Comment by joaoneivaneto** [comment]
Segunda feira de mando o problema

Em sáb., 30 de abr. de 2022 10:57, Idmar Ramos Jr. (Id) <
***@***.***> escreveu:

**Comment by idmarjr** [comment]
Estou fechando essa issue e marcando como duplicada.
Vamos concentrar as informações sobre esse problema no #347
