### ISSUE TITLE
I need help with: create sql

### ISSUE THREAD

**Issue by gabrielorei1234** [miltonbsn/brmodelo#341]
I clicked once on create the sql code from the logical model and it worked, I pressed other times but it didn't work, nothing appears

**Comment by miltonbsn** [comment]
Hi @gabrielorei1234! Thank you for reporting it.

Could you send the id of the logical model you tried ? (it is in the url)

**Comment by idmarjr** [comment]
@gabrielorei1234 Can you provide the model URL so we can investigate further?

**Comment by idmarjr** [comment]
I'm closing g this issue due to the lack of information.

We can always reopen the ticket once the model ID is provided so we can properly investigate.
