### ISSUE TITLE
Problema quanto à geração de modelagem lógica

### ISSUE THREAD

**Issue by EdmilsonDomingues** [miltonbsn/brmodelo#343]
**Describe the bug**
Tentei gerar a modelagem lógica a partir da modelagem conceitual, mas não tive sucesso. Troquei de browser e o problema foi o mesmo. Percebi que para um diagrama antigo estava OK, então hoje pela manhã refiz o diagrama, fazendo a conversão a cada passo no diagrama conceitual. Funcionou, mas uma parte não teve sucesso. Tenho vídeo gravado desta parte final. Para onde mando?
P.S.: De qualquer forma já enviei o vídeo ao professor Ronaldo.

Edmilson Domingues
edmilson.domingues1@gmail.com

===================================================================
**Steps to reproduce**
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Softwares version (please complete the following information):**
 - OS: [e.g. iOS10]
 - Browser: [e.g. Firefox 79.0, Opera 69.2]

**Additional context**

**Comment by miltonbsn** [comment]
Opa @EdmilsonDomingues, beleza? Você pode me mandar o link (url) da modelagem conceitual? 

Por ali eu consigo pegar o Id e carregar sua modelagem aqui pra encontrar o problema.

**Comment by EdmilsonDomingues** [comment]
Este é o primeiro modelo que eu fiz e não gerou modelagem lógica.
https://app.brmodeloweb.com/#!/conceptual/6297aa5a99af9e2f531d03cf

Se quiser fazer uma conferência via Meet é só enviar  link.

**Comment by miltonbsn** [comment]
O professor compartilhou seu vídeo aqui. O problema é sempre que você usa o atributo composto ? Ou o problema dessa que você mandou é outro ?

**Comment by EdmilsonDomingues** [comment]
Neste que eu te mandei não fazia nada, aí eu fui refazendo até chegar naquele do vídeo e que apontou para o atributo composto.
Não consigo te afirmar se toda vez que uso atributo composto ocorre o problema. Pode-se criar uma única entidade com o atributo composto e ver se ocorre. Queres que eu faça ou fazes aí?

**Comment by miltonbsn** [comment]
Sim, eu homologuei aqui e tá com bug mesmo no atributo composto. Ele que tá fazendo a conversão quebrar.

Vou corrigir hoje e noite

**Comment by EdmilsonDomingues** [comment]
Beleza. Tinha acabado de simular aqui (https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%226298fd7efa0d448bfb2aa153%22,%22conversionId%22:%226298fd39fa0d448bfb2aa142%22%7D) e ocorreu com uma entidade.

Obrigado pelo empenho.

**Comment by miltonbsn** [comment]
Obrigado vc por apontar o problema! Ajuda bastante a gente continuar melhorando!

Aproveitando, podes dar um suporte deixando uma estrela aqui pra gente? Ajuda bastante a gente conseguir aumentar a visibilidade e conseguir mais apoio

![image](https://user-images.githubusercontent.com/881231/171699818-61cffd01-5f26-4eca-a095-c640ac9fa465.png)

**Comment by EdmilsonDomingues** [comment]
Olá Milton.
Pelo que verifiquei, o problema ainda não teve solução, certo?

**Comment by miltonbsn** [comment]
@EdmilsonDomingues corrigido em produção. 

ps. Demorou muito mais do que o esperado pois tive um problema pessoal.

**Comment by EdmilsonDomingues** [comment]
Olá Milton. Sem problemas.
Obrigado pelo retorno. Fiz teste em um diagrama que tenha o atributo composto e está funcional.
Onde deixo a estrela?

**Comment by idmarjr** [comment]
Direto na página principal do repositório, canto direito superior :) 
https://github.com/brmodeloweb/brmodelo-app

<img width="1035" alt="Screen Shot 2022-06-18 at 16 38 47" src="https://user-images.githubusercontent.com/301545/174443360-e49ef0ea-4834-476e-b98f-5112cea1ba82.png">
