### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by mari09020** [miltonbsn/brmodelo#346]
**Describe the bug**

**Steps to reproduce**
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Softwares version (please complete the following information):**
 - OS: [e.g. iOS10]
 - Browser: [e.g. Firefox 79.0, Opera 69.2]

**Additional context**

**Comment by idmarjr** [comment]
Oi @mari09020   
Seu ticket veio sem os detalhes do problema.

Se você puder descrever o que está acontecendo, compartilhar alguns screenshots e o link do modelo que estava trabalhando quando o problema aconteceu pra que a gente possa investigar seria ótimo :)
