### ISSUE TITLE
Botão de reportar bug obstruindo ações no painel esquerdo da interface

### ISSUE THREAD

**Issue by vitorhoracio** [miltonbsn/brmodelo#347]
O elemento para reporte de erro fica posicionado em cima dos botões de cancelar e aceitar.
![image](https://user-images.githubusercontent.com/69847890/174069476-5f386e62-a728-4fce-8fe8-a6299dfbb5cb.png)

**Comment by miltonbsn** [comment]
@vitorhoracio Vamos corrigir isso na próxima versão! Deve sair no começo da próxima semana

**Comment by idmarjr** [comment]
Fix:  https://github.com/brmodeloweb/brmodelo-app/pull/321  
Nos próximos dias vamos disponibilizar em produção junto com outros bug fixes. :) 

Ping: #338

**Comment by miltonbsn** [comment]
Em produção
