### ISSUE TITLE
BR model problem SQL

### ISSUE THREAD

**Issue by DaniloGK** [miltonbsn/brmodelo#365]
My Logic Model in BRMW is not creating the SQL code.

https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%2262e8453dd1f7ba40911968a9%22,%22conversionId%22:%22%22%7D

**Comment by miltonbsn** [comment]
Hi @DaniloGK! 

I tested here and it seens to be working fine! The sql generated was:

CREATE TABLE PETS 
( 
 ID_PET INT PRIMARY KEY,  
 DS_NOME_PET VARCHAR(n) NOT NULL,  
 DS_RACA_PET VARCHAR(n) NOT NULL,  
 DT_NASCIMENTO DATE NOT NULL,  
 FL_VACINACAO_OK INT NOT NULL,  
 ID_CLIENTE INT NOT NULL,  
); 

CREATE TABLE CLIENTE 
( 
 ID_CLIENTE INT PRIMARY KEY,  
 DS_NOME_CLIENTE VARCHAR(n) NOT NULL,  
 DS_ENDERECO VARCHAR(n) NOT NULL,  
 NM_ENDERECO INT NOT NULL,  
 DS_COMPLEMENTO VARCHAR(n),  
 DT_NASCIMENTO DATE NOT NULL,  
 NM_TELEFONE INT NOT NULL,  
 NM_DD_TELEFONE INT NOT NULL,  
 UNIQUE (DS_NOME_CLIENTE)
); 

CREATE TABLE CALENDARIO 
( 
 ID_CALENDARIO INT PRIMARY KEY,  
 DT_DATA DATE NOT NULL,  
 DS_DIA_SEMANA VARCHAR(n),  
 DS_MES VARCHAR(n),  
 NM_ANO INT,  
 FL_FERIADO INT NOT NULL,  
 FL_FINAL_SEMANA INT NOT NULL,  
); 

CREATE TABLE SERVICOS 
( 
 ID_SERVICO INT PRIMARY KEY,  
 DS_SERVICO VARCHAR(n) NOT NULL,  
 NM_VALOR_SERVICO FLOAT NOT NULL,  
); 

CREATE TABLE CONTRATO 
( 
 ID_CONTRATO INT PRIMARY KEY NOT NULL,  
 ID_CLIENTE INT NOT NULL,  
 ID_PET INT NOT NULL,  
 ID_CALENDARIO INT NOT NULL,  
 ID_SERVICO INT,  
 ID_FUNCIONARIO INT NOT NULL,  
 ID_AGENDA INT,  
); 

CREATE TABLE FUNCIONARIO 
( 
 ID_FUNCIONARIO INT PRIMARY KEY,  
 DS_NOME_FUNCIONARIO VARCHAR(n) NOT NULL,  
 DT_NASCIMENTO DATE NOT NULL,  
 DT_INICIO_FERIAS DATE NOT NULL,  
 DT_FIM_FERIAS DATE,  
); 

CREATE TABLE AGENDA 
( 
 ID_AGENDA INT PRIMARY KEY,  
 NM_HORARIO_INICIO INT NOT NULL,  
 NM_HORARIO_FIM INT NOT NULL,  
 CHECK (NM_HORARIO_INICIO > 800 AND NM_HORARIO_FIM <= 1800)
); 

ALTER TABLE PETS ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
ALTER TABLE CONTRATO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
ALTER TABLE CONTRATO ADD FOREIGN KEY(ID_PET) REFERENCES PETS (ID_PET)
ALTER TABLE CONTRATO ADD FOREIGN KEY(ID_CALENDARIO) REFERENCES CALENDARIO (ID_CALENDARIO)
ALTER TABLE CONTRATO ADD FOREIGN KEY(ID_SERVICO) REFERENCES SERVICOS (ID_SERVICO)
ALTER TABLE CONTRATO ADD FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
ALTER TABLE CONTRATO ADD FOREIGN KEY(ID_AGENDA) REFERENCES AGENDA (ID_AGENDA)

**Comment by miltonbsn** [comment]
@DaniloGK Closing as we didn't have return...
