### ISSUE TITLE
Atributo composto sendo inserido N vezes

### ISSUE THREAD

**Issue by ja0x01** [miltonbsn/brmodelo#368]
Fala, galera, tudo certo? Espero que sim. 
Estou abrindo essa issue para reportar um bug que encontrei durante o desenvolvimento de um trabalho para a faculdade utilizando o brModelo. Basicamente, eu inseri um atributo composto uma única vez e N instâncias dele foram inseridas no meu projeto.  Eu percebi que o mesmo estava mais escuro que os outros (parecendo ter muitas camadas):

![elemento-attr-bugado](https://user-images.githubusercontent.com/92492845/185515740-715fc75f-ec85-41e5-b8d2-54b25427b9fe.png)

Assim, resolvi tentar entender o que aconteceu. Percebi, então, que o atributo composto não foi inserida só uma vez, e sim 17 (como dá pra ver no print)

![atributo-bugado-dom](https://user-images.githubusercontent.com/92492845/185515712-d1d6ba44-6ca9-46b8-b640-73e746fa1172.png)

Eu consegui salvar o meu projeto rodando um ```for``` e removendo os elementos de atributo composto com base no id, porém estou reportando o ocorrido para uma possível correção.

**Comment by miltonbsn** [comment]
Opa @joaomarcelogomes, beleza? Obrigado por reportar!

Tu tá conseguindo replicar esse erro? Eu tentei aqui de tudo quanto é jeito e não consegui

**Comment by ja0x01** [comment]
Fala @miltonbsn, beleza? Me desculpe pela demora.

Então, eu estava tentando replicar ele agora de manhã depois que vi sua resposta e eu também não estou conseguindo. Espero que tenha sido algo extremamente específico daquele momento mesmo!

Valeu!!
