### ISSUE TITLE
Gerar SQL

### ISSUE THREAD

**Issue by rafaelporcino** [miltonbsn/brmodelo#371]
Após toda a modelagem não está sendo possível "Gerar SQL". 
Clicando na opção não executa nada, nem mensagem de erro, nada.

Grato.

**Comment by miltonbsn** [comment]
Ei Rafael, perdi essa issue aqui.

Podes colar o link da tua modelagem lógica?

**Comment by idmarjr** [comment]
Vou encerrar esse ticket por inatividade.  
Lembrando que a gente sempre pode reabrir ele quando o link da modelagem for compartilhado ou se o problema aparecer em outros modelos.
