### ISSUE TITLE
User credentials exposed on request payload.

### ISSUE THREAD

**Issue by Victor-Manoel-Public** [miltonbsn/brmodelo#374]
### User credentials exposed on request payload.
I was trying to login and my password was incorrect, for some reason, I decided to open the "Network" tab of the browser and saw that in the payload of the request there is an exposure of _username_ and _password_.

---

### Steps to reproduce:
1. There is a 404 error on the login screen.

![image](https://user-images.githubusercontent.com/81167569/195215521-cfd72ba1-5ff7-4fd7-9223-01b27b5d9e4f.png)

2. When clicking on the _login_ error and on _Payload_ property, we can see the exposed credentials

![image](https://user-images.githubusercontent.com/81167569/195215791-5f9b9d04-9f99-4a3f-9fd0-d8375f168989.png)

When entering the correct password and then logging in, the credentials still remain in _login_
![image](https://user-images.githubusercontent.com/81167569/195216905-6b207e93-050a-4147-a649-78c146baa8b1.png)

### Extra info
I think it's a good idea to encrypt the _password_ and _username_ or remove them from the request response.

**Comment by miltonbsn** [comment]
@Victor-Manoel-Public good catch! Thank you...

I will fix this tonight!

Would you mind give us a star to help us to get more support? It's all by our own

Thank you again mate

**Comment by Victor-Manoel-Public** [comment]
Hey, thank you for the response!

I didn't get to see the source code but from what I saw in your last 5 commits, I believe that the server shouldn't return any credential, just some code that represents the status code with some generic error.
In the case of login, when the password or email is wrong, just return the error of invalid credential and the [http code 401](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/401) inside an object, for example:
{
"status_code":401,
"message": "Email ou senha inválido(s).",
"error": true
}
Upon successful login, just redirect to home without any return.

These are just guesses that I believe bring more security.
