### ISSUE TITLE
Salvamento do projeto automático a cada alteração.

### ISSUE THREAD

**Issue by matheusbarros2002** [miltonbsn/brmodelo#380]

**Comment by idmarjr** [comment]
Oi @matheusbarros2002  
Obrigado pela sugestão. 

Essa é uma funcionalidade que nós gostaríamos muito de adicionar ao BRMW, o problema é que o salvamento automático aumenta drasticamente o uso do servidor e do banco de dados.

O BRMW é disponibilizado de graça pra todo mundo mas existe um custo pra mantê-lo no ar que é bancado pelo time. Adicionar essa funcionalidade significa aumentar exponencialmente esse custo, o que inviabilizaria manter o app sem custo pros usuários. 

Por esse motivo, auto-save, apesar de ser algo que gostaríamos muito de implementar, infelizmente está fora de cogitação por hora. 😢

**Comment by idmarjr** [comment]
Estou encerrando essa issue já que por hora não temos planos de adicionar salvamento automático como explicado no comentário acima.
