### ISSUE TITLE
Precisa da barra de rolagem horizontal

### ISSUE THREAD

**Issue by gladsonsimoes** [miltonbsn/brmodelo#381]
### Sua sugestão de melhoria é relacionada a algum problema?

Sim, o problema é em relação com a produtividade que faço o diagrama conceitual , pois quero ver o outra parte eu tenho que usar os botões do teclado para ir para o lado

---

### Descreva sua ideia de como resolver o problema

Acho a melhor forma é integrar a funcionalidade e adicionar a barra horizontal.

---

### Informações extras

Se for no CSS o comando seria:

 ~~~css
 overflow-x: scroll;
~~~
https://backefront.com.br/barra-rolagem-div/

**Comment by gladsonsimoes** [comment]
Sim, o problema é em relação com a produtividade que faço o diagrama conceitual , pois quero ver um pedaço do diagrama não posso devido á falta dessa funcionalidade

**Comment by idmarjr** [comment]
Oi @gladsonsimoes 

Obrigado pela sugestão! :)

A área de trabalho do BRMW é um canva SVG e por isso sua sugestão de implementar a barra de rolagem com CSS não funcionaria assim tão diretamente.

Em todo caso, temos planos de reimplementar como o canvas funciona em um futuro breve, isso inclui a forma com que ele é gerado ao criar uma modelagem nova e também comportamentos de usabilidade como a navegação pelo canvas.


Por hora uma solução que pode amenizar esse problema é você segurar a `barra de espaço` e _clicar e arrastar_ para navegar livremente pelo canvas.

Nessa sessão da documentação tem mais detalhes sobre a funcionalidade e também um vídeo demonstrando o uso:

> [Movendo livremente pelo canvas - BRMW Docs](https://docs.brmodeloweb.com/#/canvas-navigation/README?id=movendo-livremente-pelo-canvas)

Espero que isso ajude :)
