### ISSUE TITLE
Não consigo Gerar SQL

### ISSUE THREAD

**Issue by marcos-henrique-tech** [miltonbsn/brmodelo#387]
### Link da modelagem

Adicione aqui o link da modelagem na qual você estava trabalhando quando encontrou o problema.

---

### Descreva o problema

Fiz um modelo conceitual, no qual depois converti para o modelo lógico do banco de dados. Agora quero gerar o sql para construção do banco e infelizmente, quando clico no botão nada acontece.

---

### Passos para reproduzir

1. Na tela de modelagem lógica
1. Selecione a opção Gerar Sql
1. Nada acontece

---

### Screenshots e/ou video

https://user-images.githubusercontent.com/80632969/207208211-5f74fa8f-cc1e-4b8f-a9bd-00ec86a7e03c.mp4

---

### Sistema operacional e navegador

 - Windows 11 PRO
 - MS Edge

---

### Informações extras

Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by miltonbsn** [comment]
@midnightbr beleza? manda o id da sua modelagem aí (fica na url)

**Comment by marcos-henrique-tech** [comment]
Tudo bom. Segue o id:
modelid : 638b69fdf5cc32253f9d6e45

**Comment by miltonbsn** [comment]
@midnightbr corrigido! Se puder deixar uma estrela aí no projeto ajuda bastante a gente a popularizar e quem sabe ganhar algum apoio :)

**Comment by marcos-henrique-tech** [comment]
Obrigado. Pode deixar, gostei muito do projeto.
