### ISSUE TITLE
CARDINALIDADE

### ISSUE THREAD

**Issue by mmToscano** [miltonbsn/brmodelo#388]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Adicione aqui sua pergunta

**Comment by idmarjr** [comment]
Oi @mmToscano 
Você pode dar mais detalhes do problema?

**Comment by idmarjr** [comment]
Por hora vou encerrar essa _issue_ devido a falta de informação.  
Lembrando que sempre podemos reabrir issues se mais detalhes sobre o problema forem fornecidos. 😄
