### ISSUE TITLE
Colocar preferências de usuário urgente, incluindo a opção de deletar a conta

### ISSUE THREAD

**Issue by luis-mendes018** [miltonbsn/brmodelo#390]
Não faz sentido essas configurações estarem ausentes no sistema!

**Comment by idmarjr** [comment]
Oi @luis-mendes018 obrigado pela sugestão.

Ja temos uma issue criada e designs prontos para adicionar essas opções no BRMW

https://github.com/brmodeloweb/brmodelo-app/issues/182

No momento o que nós falta é tempo pra implementar essas funcionalidades. 

Se você tiver disponibilidade pra nos ajudar, fica a vontade pra abrir um pull request com isso.

**Comment by idmarjr** [comment]
Dito isso, por hora, se você quiser deletar sua conta, por favor mande um e-mail para brmodeloweb@gmail.com informando o e-mail com qual a conta foi criada pra que a gente possa deletar o usuário e todas as modelagens vinculadas a conta.

**Comment by luis-mendes018** [comment]
muito obrigado.

**Comment by miltonbsn** [comment]
Conta removida
