### ISSUE TITLE
Erro ao gerar SQL

### ISSUE THREAD

**Issue by JeffersonDallalibera** [miltonbsn/brmodelo#392]
### Link da modelagem
https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%2263ac46f42ee8ede0cf230d6b%22%7D

---

### Descreva o problema
Ao salvar, ele salva corretamente porem nao gera o SQL quando solicitado.

---

### Passos para reproduzir
1. No modelo logico, clicar no botao "Gerar SQL". ira perceber que ele nao gera.

---

### Screenshots e/ou video
![image](https://user-images.githubusercontent.com/83378566/209821386-41382ed0-673e-4794-b8c5-aa93e1b99da5.png)

---

### Sistema operacional e navegador
Windows.
Google Chrome

---

### Informações extras
No console ele da o erro "Cannot read properties of undefined (reading 'name')"

**Comment by miltonbsn** [comment]
Oi @JeffersonDallalibera, obrigado por reportar. Corrigimos esse problema na ultima versão.
