### ISSUE TITLE
Importação de diagrama da versão desktop

### ISSUE THREAD

**Issue by italouelisson** [miltonbsn/brmodelo#399]
Prezados, uma função interessante seria a possibilidade de importação dos diagramas da ferramenta .jar (Desktop).

Att.
Ítalo Uelisson

**Comment by idmarjr** [comment]
Oi @italouelisson , obrigado pela sugestão.  
A Issue  #76 é relacionada a essa feature.

Infelizmente a implementação dessa funcionalidade caiu de prioridade por hora. Mas em algum momento vamos retornar e finalizer a funcionalidade.

Por hora vou marcar essa issue como duplicada pra que possamos discutir o assunto em uma única issue.
