### ISSUE TITLE
Compartilhamento de projeto

### ISSUE THREAD

**Issue by alancarvalho1** [miltonbsn/brmodelo#401]
Compartilhar projetos com outras pessoas para poderem mexer

**Comment by idmarjr** [comment]
Obrigado pela sugestão @alancarvalho1 !  
Estamos explorando algumas possibilidades de como implementar essa funcionalidade mas infelizmente não temos nenhuma previsão de quando isso estará disponível :(

---

Related to #227

**Comment by miltonbsn** [comment]
Feature em produção #518
