### ISSUE TITLE
Botão Gerar SQL não funciona

### ISSUE THREAD

**Issue by GGroff15** [miltonbsn/brmodelo#404]
### Link da modelagem
https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%2263fe4929a660eb5e872ad57a%22,%22conversionId%22:%22%22%7D

---

### Descreva o problema
Na modelagem do modelo lógico, ao tentar gerar o código SQL clicando no botão "Gerar SQL" nada acontece.

---

### Passos para reproduzir
1. Na tela de modelagem lógica
2. Ao clicar no botão "Gerar SQL"
3. Nada acontece.

---

### Screenshots e/ou video
![image](https://user-images.githubusercontent.com/62566917/221954517-c224bc42-bd16-45ce-898e-d638820f232e.png)

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
Windows 11

 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo
Microsoft Edge

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by idmarjr** [comment]
Oi @GGroff15  
Você pode compartilhar o link da modelagem, por favor?

**Comment by GGroff15** [comment]
> Oi @GGroff15 Você pode compartilhar o link da modelagem, por favor?

Claro! Segue

https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%2263fe4929a660eb5e872ad57a%22,%22conversionId%22:%22%22%7D

**Comment by Olkaniz** [comment]
Não esta gerando o SQL devido a problema na inserção de PK ou FK, neste caso esta em "Tenent" onde o id PK esta com a seleção FK ativa.
