### ISSUE TITLE
Movimentação usando click do scroll

### ISSUE THREAD

**Issue by Luiizfellipee** [miltonbsn/brmodelo#405]
### Sua sugestão de melhoria é relacionada a algum problema?

Para melhor navegação poderia ter a opção de colocar o scroll com a funcionalidade de movimentar a área utilizada.
A primeiro momento não tenho a solução, mas caso venha a ter alguma ideia vamos discutindo.
Obrigado e vocês são excelentes!

**Comment by idmarjr** [comment]
Oi @Luiizfellipee 

Faz alguns meses nós implementamos uma forma de melhorar a navegação no canvas dos modelos.

Ao segurar a barra de espaço + clickar e arrastar você consegue navegar livremente pelo canvas.
Na documentação tem mais detalhes: [Movendo livremente pelo canvas - BRMW Docs](https://docs.brmodeloweb.com/#/canvas-navigation/README?id=movendo-livremente-pelo-canvas)

**Comment by idmarjr** [comment]
Vou marcar essa issue como resolvida. Mas se a solução que a gente tem hoje não resolver totalmente o seu problema, comenta aqui com mais detalhes que a gente reabre o ticket. :)
