### ISSUE TITLE
Não consigo gerar SQL

### ISSUE THREAD

**Issue by patrickbarros6** [miltonbsn/brmodelo#409]
### Link da modelagem
https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%2264162b85b2ae9e56d9e6d2a7%22,%22conversionId%22:%22%22%7D

---

### Descreva o problema
Quando clico no botão "Gerar SQL" não acontece nada.

---

### Sistema operacional e navegador
WIndows 10
Edge - Version 111.0.1661.44 (Official build) (64-bit)

**Comment by miltonbsn** [comment]
Oi @patrickbarros6, obrigado por reportar. Corrigimos esse problema na ultima versão.
