### ISSUE TITLE
Como eu exporto o arquivo do projeto?

### ISSUE THREAD

**Issue by GabrielMasiiero** [miltonbsn/brmodelo#410]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Como eu exporto o arquivo do projeto?

**Comment by idmarjr** [comment]
Oi @GabrielMasiiero 

No momento essa opção ainda não está disponível.  
Na issue #75 existe algum trabalho sendo feito nessa linha mas ainda sem previsão de ser finalizado 😢

**Comment by miltonbsn** [comment]
Feature em produção #518
