### ISSUE TITLE
Selecionar e Arrastar

### ISSUE THREAD

**Issue by klnyagor** [miltonbsn/brmodelo#412]
### Sua sugestão de melhoria é relacionada a algum problema?
Não consegui achar como selecionar a modelagem já feita e arrastar, somente para mudar a posição, tendo que fazer isso elemento por elemento

---

### Descreva sua ideia de como resolver o problema
Não faço ideia, boa sorte.

---

### Informações extras
O objetivo é somente posicionar os elementos(ex: entidade, atributos, relacionamento, etc), de forma que eu possa selecionar todos e reposicionar na tela

**Comment by idmarjr** [comment]
Oi @klnyagor 

Essa funcionalidade existia no BRMW até um tempo atrás mas tivemos que desabilita-lá temporariamente.  
Em breve a opção de arrastar para selecionar vai voltar. :)
