### ISSUE TITLE
Import para Brmodelo Web

### ISSUE THREAD

**Issue by LohanConrado** [miltonbsn/brmodelo#413]
Não foi possível importar um modelo do brmodelo desktop.

Seria possível elaborar uma funcionalidade para abrir um arquivo do computador no formato usado pelo brmodelo em Java?

**Comment by idmarjr** [comment]
Oi @LohanConrado  
Obrigado pela sugestão de funcionalidade.

Infelizmente implementar essa funcionalidade não é algo tão trivial quanto parece por algumas questões relacionadas a segurança.

Mas na issue #76 temos algum progresso nessa linha.  
Infelizmente não consigo te dar uma previsão de quando (Ou mesmo se) essa funcionalidade vai chegar 😢

**Comment by idmarjr** [comment]
Como não temos previsão de implementar essa feature, vou encerrar essa issue.
Mais uma vez, obrigado pela sugestão 😄
