### ISSUE TITLE
Sem resposta do sistema ao clicar no botão "Gerar Sql"

### ISSUE THREAD

**Issue by CarlosVinicius3258** [miltonbsn/brmodelo#414]
### Link da modelagem
[https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%22642c0dcee88bac2b73e88a9f%22,%22conversionId%22:%22%22%7D](https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%22642c0dcee88bac2b73e88a9f%22,%22conversionId%22:%22%22%7D)

---

### Descreva o problema
Não consigo gerar o código sql do modelo. Ao clicar no botão não há nenhuma resposta do sistema.

---

### Passos para reproduzir
1. Na tela de edição do modelo, selecione a opção "Gerar Sql".

---

### Screenshots e/ou video
![image](https://user-images.githubusercontent.com/44340753/231145362-b817b441-031b-490d-a641-5240d3fe13f9.png)

---

### Sistema operacional e navegador
 - Windows 10
 - Chrome - Versão 112.0.5615.49 (Versão oficial) 64 bits

---

### Informações extras
Ações feitas no dia 11/04, porém dia 10/04 estava funcionando normalmente.

**Comment by idmarjr** [comment]
Oi @CarlosVinicius3258 

Antes de qualquer coisa, muito obrigado pela _issue_ competa e bem descrita. Isso ajuda muito a gente. :) 

Eu acredito que isso tenha a ver com um bug que já estamos cientes mas que ainda não foi corrigido.  
Esse "erro silencioso" acontece quando sua modelagem não é válida de alguma forma.

Geralmente isso tem a ver com alguma conexão entre entidades que visualmente parece existir mas que na prática os elementos não estão conectados.

Por conta disso, a operação de gerar o SQL falha silenciosamente.

Minha sugestão é que você passe um pente fino pra ter certeza de que todas as conexões e relações estão corretas. Se tu não encontrar nada errado, me avisa aqui que vou investigar mais a fundo ,

**Comment by miltonbsn** [comment]
Oi @CarlosVinicius3258, obrigado por reportar. Corrigimos esse problema na ultima versão.
