### ISSUE TITLE
impressão

### ISSUE THREAD

**Issue by EdsonMuniz1844** [miltonbsn/brmodelo#415]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Adicione aqui sua pergunta

**Comment by idmarjr** [comment]
Oi @EdsonMuniz1844 

Sua issue não veio preenchida.  
Qual sua dúvida?

**Comment by idmarjr** [comment]
Estou fechando essa _issue_ por hora.
Lembrando que sempre podemos reabri-lá quando tivermos mais informações. :)
