### ISSUE TITLE
Como abrir um arquivo no BrModelo

### ISSUE THREAD

**Issue by gabriel585** [miltonbsn/brmodelo#416]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Adicione aqui sua pergunta

**Comment by idmarjr** [comment]
Oi @gabriel585 
Eu acredito que sua dúvida tenha a ver com o BRModelo Desktop, porém não tenho certeza.  
Você pode dar mais detalhes do que exatamente com o que precisa de ajuda?

**Comment by gabriel585** [comment]
então estou tentando importar um projeto oriundo do BrmodeloWeb, porem não sei se é possível, já que na versão desktop não abre. Desde de já agradeço

**Comment by idmarjr** [comment]
Apesar de terem nomes parecidos, o BRModeloWeb (BRMW) e o BRModelo (Desktop) são projetos independentes e por hora não existe compatibilidade entre eles.

O que quero dizer é: Você não vai conseguir importar um modelo criado pelo app desktop na versão web e vice-versa.

Nós temos a intenção de desenvolver essa funcionalidade um dia porém não existe previsão pra tal :(

**Comment by gabriel585** [comment]
Obrigado pela resposta. Então outra pequena dúvida, é possível importar ou exportar um arquivo para o BrModeloWeb. Pois fazendo um trabalho em conjunto acabei recebendo um arquivo oriundo do BrmodeloWeb com o arquivo .brM. Obrigado pelo excelente suporte aqui oferecido!

**Comment by idmarjr** [comment]
Arquivos `.brm` são criados usando o BRModelo Desktop.  
Não é possível exportar arquivos pelo https://app.brmodeloweb.com. Todos os projetos criados nele vivem só na web.

Pra abrir esse arquivo `.brm` você vai precisar instalar a versão desktop.

- https://github.com/chcandido/brModelo
- http://www.sis4.com/brModelo/download.html

**Comment by gabriel585** [comment]
Muito obrigado pelo suporte! e parabéns pelo projeto!

Tenha um excelente dia
