### ISSUE TITLE
campo de modelagem

### ISSUE THREAD

**Issue by liceangela** [miltonbsn/brmodelo#422]
### Link da modelagem
https://app.brmodeloweb.com/#!/conceptual/6449643ece81ec6f392a9555

---

### Descreva o problema
Não consigo ter acesso ao restante do campo de edição, a barra de rolagem não funciona.

---

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by idmarjr** [comment]
Oi @liceangela 

Você pode me dar mais detalhes? Qual barra de rolagem?
Se possível adicionar um _screenshot_ ou video do problema pra que a gente possa entender melhor o que está acontecendo 😅

**Comment by idmarjr** [comment]
Vou encerrar essa issue por falta de informação pra que possamos investigar o problema.
Lembrando que podemos reabri-la no futuro se for preciso. 😄
