### ISSUE TITLE
brmodelo

### ISSUE THREAD

**Issue by rzanin80** [miltonbsn/brmodelo#423]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Adicione aqui sua pergunta

**Comment by idmarjr** [comment]
Oi @rzanin80 tudo bem?

Você não adicionou a pergunta qua do criou a issue. 

Qual sua dúvida?
