### ISSUE TITLE
Como mudo a cardinalidade dos relacionamentos?

### ISSUE THREAD

**Issue by amateratsoo** [miltonbsn/brmodelo#424]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Como mudo a cardinalidade dos relacionamentos? Não encontro a resposta mesmo na documentação

**Comment by hosanabarcelos** [comment]
Oi, @amateratsoo! :)

Com o hover na cardinalidade, um ícone azul é exibido e você consegue fazer a alteração:
![image](https://github.com/brmodeloweb/brmodelo-app/assets/55986782/d38bdcc8-f818-4f5b-9f07-dd9a99dbf620)

Estando com a sidebar expandida presente no lado direito, você visualiza as opções:
![image](https://github.com/brmodeloweb/brmodelo-app/assets/55986782/f3ca24cc-bfdc-4c5b-b3d2-72e8909d437f)
![image](https://github.com/brmodeloweb/brmodelo-app/assets/55986782/57ece882-d1a5-480b-bd00-aa956f4b2285)

**Comment by idmarjr** [comment]
Oi @amateratsoo , a resposta da @hosanabarcelos responde sua pergunta?
Se sim, vou encerrar esse ticket. :)
