### ISSUE TITLE
Preciso de ajuda com o Brmodeloweb

### ISSUE THREAD

**Issue by DanyMenezes** [miltonbsn/brmodelo#425]
Prezados Desenvolvedores, boa noite, tudo bem?

Estou utilizando o brmodeloweb para prática de criação de modelos conceitual e lógico para a disciplina de Banco de Dados do meu curso de graduação. Gostei bastante e consegui montar o modelo que eu precisava mas senti falta de algumas funcionalidades tipo **como eu posso imprimir, exportar, salvar meu mapa, configurar a página, tamanho, fonte etc**.

Vcs pensam em implantar essas funcionalidades?
Eu não tenho experiência nessa área mas estou me interessando em aprender mais.
Obrigada pela atenção,

Daniela Menezes

**Comment by hosanabarcelos** [comment]
Oi, Daniela! :)

A opção de imprimir existe nas opções da seção superior. Acredito que você colocando o layout no modo paisagem, ficará tudo certo.
![image](https://github.com/brmodeloweb/brmodelo-app/assets/55986782/d86a7e08-a70f-4d62-89fc-74370545f352)

Após realizar o login, seus diagramas ficam salvos na sua conta na seção de modelagens:
![image](https://github.com/brmodeloweb/brmodelo-app/assets/55986782/859207c0-374e-4f0f-a37d-fffd371b35cd)

Quanto à configuração de páginas e estilização, acredito que possa ser implementado futuramente. Mas a estilização atual consegue compor muito bem os itens necessários para um diagrama.

**Comment by DanyMenezes** [comment]
Boa tarde, Hosana! 
Muito obrigada pelo retorno.

Vou te mostrar abaixo como eu vejo o site aqui. Realmente está diferente desses exemplos que vc me mandou.
Se puder me orientar, pois acho que estou fazendo algo errado.

Muito obrigada!

**Comment by idmarjr** [comment]
Oi @DanyMenezes 

Sua última mensagem veio sem as imagens em anexo. 😞 
Antes de responder suas dúvidas é bom esclarecer a diferença entre [BRModeloWeb (BRMW)](https://brmodeloweb.com) e [BR Modelo](http://www.sis4.com/brModelo/). Apesar dos nomes quase idênticos esses são projetos independentes. 

O **BRMW** é uma versão que roda no seu navegador e não necessita ser instalado no computador, porém é preciso que o usuário [crie uma conta](https://app.brmodeloweb.com/#!/register) para utilizá-lo.

Já o **BRModelo** é um software tradicional que precisa ser baixado e instalado normalmente mas não exige criação de conta para tal.

Com isso esclarecido, segue algumas observações pra suas dúvidas:

1. Imprimir modelo
Como a @hosanabarcelos comentou, a opção de imprimir já existe porém, dependendo do tamanho do seu modelo imprimir a visualização completa em uma única página pode ser um problema. Nesses casos a recomendação é que você tire um _screenshot_ do modelo e imprima a imagem. Assim você tem mais controle das configurações da impressão.

2. Exportar modelo
Essa opção ainda não está disponível no BRModeloWeb (BRMW). Existe um trabalho em andamento pra adicionar essa funcionalidade ( #75 ) porém não temos previsão de quando (Ou mesmo se) essa funcionalidade vai ser finalizada.

3. Salvar modelo
Na página da modelagem, o botão para salvar o modelo está no canto superior direito da sua tela.
Uma vez salvo o modelo vai estar disponível na [listagem de modelos](https://app.brmodeloweb.com/#!/main) como a @hosanabarcelos comentou.

| Salvar modelo | Listagem de modelos |
| -------------- | ---------------------- |
|  ![app brmodeloweb com_(mDPI notebook)](https://github.com/brmodeloweb/brmodelo-app/assets/301545/c38237c5-888a-48ff-80a0-2b9a8d5ab1d6) |  ![app brmodeloweb com_(mDPI notebook) (1)](https://github.com/brmodeloweb/brmodelo-app/assets/301545/4230c5ee-6f51-49cd-8c11-a7a8cf73cbf8) |

4. Configurar página
Hoje a área de trabalho de um modelo (_Canvas_) é gerada de acordo com o tamanho da tela do seu dispositivo. Essa área de trabalho cresce automaticamente ao mover elementos para a área próxima as bordas do _canvas_. Esse comportamento deve ser mudado em um futuro próximo também. Você pode encontrar mais detalhes na issue #238 

5. Configurações de fonte
No momento não é possível alterar nenhuma configuração referente a estilos de fonte no BRMW e infelizmente não temos previsão para adicionar essa funcionalidade.

**Comment by DanyMenezes** [comment]
Boa tarde, Senhores!
Muito obrigada à todos pelos esclarecimentos e pela atenção.

Já estou me familiarizando com a ferramenta e ela é bastante útil (na minha opinião uma das melhores!) por ser simples, objetiva e de fácil compreensão. Quero ser informada das atualizações e novas funcionalidades implementadas.

Agradeço novamente e ensejo muito mais sucesso aos envolvidos nesse relevante projeto.

Atenciosamente,
Daniela Menezes
