### ISSUE TITLE
massa

### ISSUE THREAD

**Issue by arthurpimentel10** [miltonbsn/brmodelo#426]
### Link da modelagem
Adicione aqui o link da modelagem na qual você estava trabalhando quando encontrou o problema.

---

### Descreva o problema
Adicione aqui uma breve descrição do problema.

---

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by idmarjr** [comment]
Oi @arthurpimentel10 seu ticket veio sem uma explicação do problema que você encontrou. Por conta disso vou fechar o ticket. Quando você nos der mais detalhes do problema reabrimos esse ticket.

Um abraço.
