### ISSUE TITLE
Erro ao gerar script lógico

### ISSUE THREAD

**Issue by Patchelli** [miltonbsn/brmodelo#430]
### Link da modelagem
Adicione aqui o link da modelagem na qual você estava trabalhando quando encontrou o problema.
Modelagem lógica

---

### Descreva o problema
Adicione aqui uma breve descrição do problema.
Após mudar os dados primitivos e atribuir as fk , clico no gerar o script  e não gera.

Seguinte erro no console :

```
9271.js:2 TypeError: Cannot read properties of undefined (reading 'name')
    at c (272.js:1:8199)
    at Object.generate (272.js:1:9595)
    at d.generateSQL (272.js:1:35980)
    at fn (eval at compile (271.js:2:380755), <anonymous>:4:181)
    at i (271.js:2:426527)
    at u.$eval (271.js:2:377487)
    at u.$apply (271.js:2:377732)
    at HTMLAnchorElement.<anonymous> (271.js:2:426612)
    at Pe (271.js:2:292181)
    at HTMLAnchorElement.n (271.js:2:295051)
(anonymous) @ 271.js:2
DevTools failed to load source map: Could not load co
```

---

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by miltonbsn** [comment]
Oi @Patchelli, obrigado por reportar. Corrigimos esse problema na ultima versão.
