### ISSUE TITLE
relação

### ISSUE THREAD

**Issue by J1R429** [miltonbsn/brmodelo#431]
como é possivel mudar o relacionamento das tabela? .. os 0,1 0,n 1,n

**Comment by marciogadelha** [comment]
Seleciona a linha do relacionamento e clica no "i" com o círculo azul. Quando fizer isso, aparece a opção de mudar a cardinalidade na lateral, como na imagem abaixo:
![Relacionamento BrModelo Web](https://github.com/brmodeloweb/brmodelo-app/assets/5349180/4dd9f3d0-5a78-4373-8aee-398594f6da4f)

**Comment by miltonbsn** [comment]
Boa @marciogadelha! Muito obrigado pela contribuição!

**Comment by J1R429** [comment]
Obrigada pela dica
vou tentar novamente, pra mim na hora só tinha aparecido o x vermelho.

obrigada pela atenção


Jéssica Fernandes da Silva


________________________________
De: Milton Bittencourt ***@***.***>
Enviado: sábado, 10 de junho de 2023 10:43
Para: brmodeloweb/brmodelo-app ***@***.***>
Cc: jessicacanela ***@***.***>; Author ***@***.***>
Assunto: Re: [brmodeloweb/brmodelo-app] relação (Issue #431)


Boa @marciogadelha<https://github.com/marciogadelha>! Muito obrigado pela contribuição!
