### ISSUE TITLE
Exportar modelo para ser usado no app desktop

### ISSUE THREAD

**Issue by joaodellarmelina** [miltonbsn/brmodelo#432]

**Comment by idmarjr** [comment]
Oi @joaodellarmelina 

Sua sugestão está um pouco abstrata. Você pode dar mais detalhes da ideia?

**Comment by joaodellarmelina** [comment]
Claro! @idmarjr 

Eu precisei fazer um projeto da faculdade no brmodelo em sua versão da web e tive um problema quando precisei migrar meu projeto para o aplicativo do brmodelo.

Eu acho que seria sensacional se houvesse uma integração entre as duas aplicações.

**Comment by idmarjr** [comment]
Certo. Obrigado pelo contexto :). 
Alterei o titulo da _issue_ pra ser mais específico. Você pode atualizar ele se achar que não está de acordo.

Sobre a funcionalidade de exportar/importar... Nós tivemos várias conversas sobre adicionar essa feature no BRMW.
Existem inclusive dois merge requests ~abertos~ pra isso: #301 e #297 

Infelizmente implementar isso não é algo tão simples e vem com uma série de questões de segurança pra ambas as aplicações (Web e desktop). Por conta disso nós (por hora) suspendemos a implementação dessas funcionalidades.

Por hora não temos ideia de quando esse trabalho será retomado mas quando isso acontecer, te aviso aqui :)

**Comment by idmarjr** [comment]
Como não temos previsão de implementar essa feature, vou encerrar essa issue.
Mais uma vez, obrigado pela sugestão 😄
