### ISSUE TITLE
Problema no Login

### ISSUE THREAD

**Issue by braga0425** [miltonbsn/brmodelo#440]
Não está sendo possível logar e muito menos criar modelagens ou acessar antigas.

**Comment by miltonbsn** [comment]
@braga0425, beleza? testei aqui e parece tudo ok. Será que sua sessão tinha encerrado? tenta limpar o cache ai e me avise. PS. se vc não conseguiu fazer login, como constatou que não estava podendo acessar modelagens ?

**Comment by braga0425** [comment]
@miltonbsn pq ele já entrou logado, porém não conseguia sair e também não estava sendo possível criar uma modelagem nova, ficava carregando eternamente
mas agr testei novamente e foi possível sair, ao relogar, apareceu tudo novamente
