### ISSUE TITLE
Abrir modelos já criados

### ISSUE THREAD

**Issue by tatilimongi** [miltonbsn/brmodelo#442]
Senti falta da opção de abrir um modelo já criado pelo brModelo no brModelo Web. Caso tenha, não consegui achar onde faz isso 😅.

**Comment by idmarjr** [comment]
Oi @tatilimongi 

Essa funcionalidade ainda não existe mesmo. Infelizmente não temos previsão de implementar isso. Dar a possibilidade de importar arquivos pro BRMW vem um alguns riscos de segurança já que precisamos fazer uma série de verificação pra ter certeza de que o arquivo importado não tem nenhum tipo de _code injection_.

Pra te ser honesto, não acho que vamos implementar isso tão cedo :(

**Comment by idmarjr** [comment]
Infelizmente estamos despriorizando o desenvolvimento dessa feature. Por conta disso vou encerrar essa issue.

Pra mais detalhes: https://github.com/brmodeloweb/brmodelo-app/issues/76#issuecomment-2068186253
