### ISSUE TITLE
Não é possível fazer o login no app

### ISSUE THREAD

**Issue by Matheus788** [miltonbsn/brmodelo#444]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta

Não consigo fazer login na minha conta

**Comment by Matheus788** [comment]
Fala que não é possível fazer login

**Comment by idmarjr** [comment]
Oi @Matheus788 

Fiz uns testes aqui e consegui fazer o login com minha conta e mais algumas contas de teste.  
Provavelmente tem algo errado com seu usuário / senha.

Se tu criou sua conta pelo celular, talvez seu email foi cadastrado com a primeira letra maiúscula.
Essa letra maiúscula deveria ser ignorada, o que não está acontecendo. Isso é um bug conhecido que estamos trabalhando pra resolver.

Minha sugestão é tentar fazer o login com a primeira do email maiúscula. Se isso não resolver o problema, preciso que você me passe o email com o qual criou a conta pra que a gente possa investigar melhor.
