### ISSUE TITLE
nao consigo criar um modelo novo

### ISSUE THREAD

**Issue by IsabelleBic20** [miltonbsn/brmodelo#452]

**Comment by samarakel** [comment]
Não consigo criar um novo modelo

**Comment by miltonbsn** [comment]
Estavamos com uma indisponibilidade mas já foi resolvido!

https://docs.brmodeloweb.com/#/basics/README?id=criar-um-novo-modelo

Obrigado por reportar.

**Comment by idmarjr** [comment]
Oi @IsabelleBic20 
Tivemos uns problemas de instabilidade hoje mas ja foi tudo resolvido.

Vou encerrar a issue mas se você estiver enfrentando o problema ainda, por favor comenta aqui que reabrimos pra investigar mais a fundo. :)
