### ISSUE TITLE
Não consigo iniciar um novo projeto nem consigo salvar o que já está pronto

### ISSUE THREAD

**Issue by samarakel** [miltonbsn/brmodelo#453]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

Como iniciar um novo projeto ?

**Comment by miltonbsn** [comment]
Estavamos com uma indisponibilidade mas já foi resolvido! 

https://docs.brmodeloweb.com/#/basics/README?id=criar-um-novo-modelo

Obrigado por reportar.
