### ISSUE TITLE
Poder deletar varios componentes apertando o botão [delete]

### ISSUE THREAD

**Issue by PaulinaEster** [miltonbsn/brmodelo#456]
### Sua sugestão de melhoria é relacionada a algum problema?

Sim!! o problema é que desperdiço tempo clicando e deletando componente por componente.

---

### Descreva sua ideia de como resolver o problema

Poder deletar varios componentes apertando o botão [delete]
Gostei muito dos outros atalhos de Ctrl+S e Esc, agora só falta poder deletar com o delete.

---

**Comment by idmarjr** [comment]
Por hora os atalhos de teclado só tem efeito com elementos individuais. :(
https://docs.brmodeloweb.com/#/canvas-usage/README?id=removendo-elementos

Mas nós queremos melhorar isso em breve, inclusive removendo a necessidade de segurar `ctrl` + `backspace` pra deletar um elemento e ao invés disso a ação ser feita só com o `backspace` ou `delete`.

Se tudo der certo... Em breve isso vai estar no ar. Aí te atualizo aqui.

**Comment by CarlosEduR** [comment]
@idmarjr, já existe alguém trabalhando na feature?

**Comment by idmarjr** [comment]
Oi @CarlosEduR 

No momento não. 😔  
O update de remover a necessidade de segurar `ctrl` pra excluir um elementos já está no ar. Hoje, com um elemento selecionado você pode usar só o `backspace` pra deletar o elemento.

Já a opção de deletar múltiplos elementos quando selecionados ainda não existe e não tempos previsão de começar a trabalhar nisso. :( 

Se você tiver interesse / disponibilidade de implementar, podemos conversar sobre. 😁

**Comment by CarlosEduR** [comment]
@idmarjr legal, acredito que consigo dar uma olhada e tentar implementar.

**Comment by idmarjr** [comment]
Pô, manda a ver! :) 

Minha sugestão é abrir um pull request como draft e começar a trabalhar nisso. Se tu tiver alguma dúvida ou dificuldade, comenta direto no PR que a gente da o suporte que for necessário!

**Comment by CarlosEduR** [comment]
@idmarjr estava prestes a abrir o PR com uma solução, mas vi agora que o Milton já começou a trabalhar em cima - uma pena que não recebi notificação sobre.

:rocket:

**Comment by idmarjr** [comment]
@CarlosEduR 
Se tu já tem um branch com commits, abre o MR mesmo assim. :) 

Assim a gente pode comparar as soluções e decidir qual adotar. Ou até fazer um mix de ambas.

Cc @miltonbsn
