### ISSUE TITLE
Dois cliques no componente deve abrir a aba lateral direita de edição e já selecionar a alteração do nome 

### ISSUE THREAD

**Issue by PaulinaEster** [miltonbsn/brmodelo#458]
### Sua sugestão de melhoria é relacionada a algum problema?

É muito ruim ter que ir de um lado da tela á outro apenas para abrir o menu lateral.

---

### Descreva sua ideia de como resolver o problema
Poderia ser adicionado dois cliques a entidade ou atributo ou ao relacionamento, e quando feito isso o menu lateral direito de edição de informações poderia ser aberto e campo [nome] do menu lateral deve estar habilitado para editar.

---

**Comment by miltonbsn** [comment]
@PaulinaEster Feito :)
