### ISSUE TITLE
Navegar pela tela com o botão direito do mouse pressionado

### ISSUE THREAD

**Issue by PaulinaEster** [miltonbsn/brmodelo#459]
### Sua sugestão de melhoria é relacionada a algum problema?

É muito complicado fazer fazer o scroll pela tela sem um touchpad.

---

### Descreva sua ideia de como resolver o problema
Adicionar essa função ao botão direito do mouse, se o usuário manter pressionado o botão direito, consegue mover a tela confirme o mouse se move.

---

### Informações extras

Melhorou muito, parabéns, estão mandando muito bem!!

**Comment by idmarjr** [comment]
Oi @PaulinaEster !

Obrigado pela sugestão. O BRMW já tem uma solução próxima a sua sugestão pra navegar pelo canvas.

Se você segurar a `barra de espaço` + clickar e arrastar  você consegue navegar livremente.  
Na documentação tem mais detalhes: [Movendo livremente pelo canvas - BRMW Docs](https://docs.brmodeloweb.com/#/canvas-navigation/README?id=movendo-livremente-pelo-canvas)

Isso resolve seu problema?  
Ou Tem  tem algo que essa solução não resolve ou pode melhorar?

---

> _Melhorou muito, parabéns, estão mandando muito bem!!_

💙  Obrigado! A gente tem investindo mais e mais tempo pra continuar melhorando. BRMW. 
Fica a vontade pra mandar mais sugestões e reportar bugs que tu encontrar enquanto usa. Isso ajuda muito a gente a continuar melhorando 😃
