### ISSUE TITLE
problem: the  digrams are erased without permission user

### ISSUE THREAD

**Issue by DavidSantosDeveloper** [miltonbsn/brmodelo#465]
problem: the  digrams are erased without permission user

**Comment by idmarjr** [comment]
Oi @DavidSantosDeveloper  
Você pode dar mais detalhes sobre o problema?


Compartilhar o link do modelo pra que a gente possa investigar talvez?

**Comment by DavidSantosDeveloper** [comment]
Resolvido.

É que otem eu entrei na minha conta no brmodelo e o sistema não listava
nenhum dos diagramas que tinha salvo na conta, como se os mesmos tivessem sido
apagados. Contudo,ao entrar hoje na conta,o sistema listou normalmente os
diagramas entidade-relacionamento que tinha lá.



Em sex., 15 de set. de 2023 às 21:07, Idmar Ramos Jr. (Id) <
***@***.***> escreveu:

**Comment by idmarjr** [comment]
👍 

Se o problema acontecer novamente, fica a vontade pra reabrir essa issue pra que a gente possa investigar.
