### ISSUE TITLE
A parte visual que representa a tabela não redimensiona quando o número de colonas aumenta

### ISSUE THREAD

**Issue by Jose-Isaac** [miltonbsn/brmodelo#469]
### Link da modelagem
https://app.brmodeloweb.com/#!/logic/%7B%22modelid%22:%226511c77fbee599b212154175%22,%22conversionId%22:%22%22%7D

---

### Descreva o problema
A parte visual que representa uma tabela não redimensiona quando o número de colonas presente na tabela aumenta, dificultando assim a visualização de alguns campos.

---

### Passos para reproduzir
1. Na tela de modelagem lógica
2. Adicione uma tabela
3. Adicione mais de 7 colunas a tabela

---

### Screenshots e/ou video
![Screenshot 2023-09-25 161219](https://github.com/brmodeloweb/brmodelo-app/assets/54222439/d187c04d-305f-4eeb-aab1-e76b968681d5)

---

### Sistema operacional e navegador
 - Windows 11
 - Chrome v117.0.5938.92

**Comment by idmarjr** [comment]
Oi @Jose-Isaac 

Obrigado por reportar!  
Esse bug já existe a muito tempo e é bastante irritante 😢 
Mas infelizmente ele não está na nossa lista de prioridades por dois motivos:

1. Ele não é um impeditivo pro uso do BRMW
2. Você pode redimensionar a tabela pro tamanho desejado usando o menu contextual:
 
<img width="182" alt="Screenshot 2023-09-30 at 14 49 46" src="https://github.com/brmodeloweb/brmodelo-app/assets/301545/83c1021c-b0c8-45b8-84cd-b1ce5dd17d1f">

---

Em algum momento esse problema vai ser corrigido mas infelizmente por hora temos melhorias e bugs mais críticos que tem prioridade na fila.
