### ISSUE TITLE
Compartilhamento de modelagem

### ISSUE THREAD

**Issue by kauaumnougueira** [miltonbsn/brmodelo#470]
### Sua sugestão de melhoria é relacionada a algum problema?

Não tem relação com um problema, mas sugiro que implementem a funcionalidade de compartilhar a modelagem em tempo real para a equipe

---

### Descreva sua ideia de como resolver o problema

N/A

---

### Informações extras

N/A

**Comment by idmarjr** [comment]
Oi @kauaumnougueira 

Obrigado pela sugestão :)  
Temos algo parecido com isso sendo desenvolvido. Você pode ver mais detalhes aqui: #227 

Infelizmente a funcionalidade que estamos trabalhando não  inclui a possibilidade de mais de um usuário editar o modelo em tempo real.

Desenvolver isso é um pouco mais complexo do que parece e de quebra aumentaria **muito** o custo de manter o BRMW no ar pelos mesmo motivo que até hoje nunca implementamos a opção de auto-save (Pra saber mais: #380 )

**Comment by miltonbsn** [comment]
Feature em produção #518
