### ISSUE TITLE
Deletar

### ISSUE THREAD

**Issue by DartagnanFreire** [miltonbsn/brmodelo#473]
Não existe a possibilidade de deletar quando se está com mais de um item selecionado. Somente um por um

**Comment by idmarjr** [comment]
Oi @DartagnanFreire 

Só pra esclarecer, hoje não consideramos isso como um bug mas sim uma limitação do sistema.  
Deletar multiplos elementos ao mesmo tempo é um pouco mais complexo do que parece devido as relações entre os elementos. Por isso decidimos deixar isso de fora na implementação original.

Mas... Já temos um trabalho em andamento pra adicionar essa feature: #467

**Comment by idmarjr** [comment]
Relacionado a #456
