### ISSUE TITLE
Edição de itens

### ISSUE THREAD

**Issue by rodrigopf77** [miltonbsn/brmodelo#481]
### Link da modelagem

https://app.brmodeloweb.com/#!/conceptual/6547a7df533d15ae135c2de1

### Descreva o problema

Problemas para a seleção de itens

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by idmarjr** [comment]
Oi @rodrigopf77   
Você pode por favor dar mais detalhes sobre o problema?
O que exatamente está acontecendo de errado na seleção de itens?

**Comment by idmarjr** [comment]
Por hora estou fechando essa issue já que não temos mais detalhes do problema.
Lembrando que sempre podemos reabri-la. :)
