### ISSUE TITLE
Deleção de conta

### ISSUE THREAD

**Issue by Renato-Cruz-Jr** [miltonbsn/brmodelo#487]
Eu gostaria de deletar a minha conta, mas isso aparenta não ser possível no website.

**Comment by idmarjr** [comment]
Oi @Renato-Cruz-Jr 
Você pode excluir sua conta na página de preferências.

Pra acessar essa página, na lista de modelos, canto superior direito existe um ícone de usuário. Ao clicar nele um submenu se abrirá e nele existe um item "Preferencias":

![Screenshot 2023-11-28 at 10 51 32](https://github.com/brmodeloweb/brmodelo-app/assets/301545/192e4d46-1152-460d-93d8-df77c07450e6)

Ou, aqui tem um link direto pra lá:
https://app.brmodeloweb.com/#!/preferences

> [!WARNING]
> Pra poder deletar sua conta, antes você precisa deletar todos os seus modelos.

Por favor me avisa se você conseguir deletar a conta pra que eu possa encerrar essa _issue_

**Comment by idmarjr** [comment]
Vou encerrar essa issue como concluída. Lembrando que sempre podemos reabri-la caso necessário.
