### ISSUE TITLE
Perda de Modelos

### ISSUE THREAD

**Issue by GabrielSoares3** [miltonbsn/brmodelo#494]
Há alguns meses atrás conheci o Brmodeloweb em um MBA que fiz, criei alguns modelos como teste durante as aulas, no último mês passei a usar o Brmodeloweb para criar alguns modelos, porém hoje, quando abri minha conta, percebi que meus modelos antigos haviam sumido.

Existe um tempo limite para os modeloes expirarem?
Há possibilidade de reaver modelos que sumiram?

**Comment by idmarjr** [comment]
Oi @GabrielSoares3 !
Você pode por favor mandar um email pra `brmodeloweb[at]gmail.com` informando o email que você usa pra logar no BRMW?

Com isso a gente pode investigar o que aconteceu e recuperar seus modelos.

**Comment by GabrielSoares3** [comment]
Ok, farei isso, obrigado!!

**Comment by idmarjr** [comment]
@GabrielSoares3 Respondi seu email. Estou no aguardo de uma resposta sua pra continuar investigando o problema.

**Comment by idmarjr** [comment]
@GabrielSoares3 
Como não tive retorno seu nas últimas duas semanas, vou encerrar esse ticket.
Lembrando que sempre podemos reabri-lo.
