### ISSUE TITLE
projeto não carrega

### ISSUE THREAD

**Issue by BrunoDevRocha30** [miltonbsn/brmodelo#495]
### Link da modelagem
Adicione aqui o link da modelagem na qual você estava trabalhando quando encontrou o problema.

https://app.brmodeloweb.com/#!/conceptual/65b59c9bf4e61b2fc5530696

### Descreva o problema
Adicione aqui uma breve descrição do problema.

ao arrastar um item travou tudo. apertei o botão salvar e os tres pontinho ficaram minutos correndo e não salvou. recarreguei a pagina e agora nem esse projeto e nenhum dos outros projetos aparecem na minha minha lista.

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

![image](https://github.com/brmodeloweb/brmodelo-app/assets/109320111/d919bcfb-7205-43d3-a9e9-afcb01f06200)
![image](https://github.com/brmodeloweb/brmodelo-app/assets/109320111/2b184988-640a-40b7-a41c-a77f1f7c8269)

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by idmarjr** [comment]
Oi @BrunoDevRocha30 

Pode ser que sua sessão expirou. Em alguns casos o redirect pra tela de login não está acontecendo como esperado.
Tenta recarregar a página limpando o cache (`ctrl` + `F5`) e logar novamente no app. Acredito que isso deve resolver o problema.

Caso isso não funcione, tenta abrir uma aba anônima no seu navegador e logar no [app.brmodeloweb.com](https://app.brmodeloweb.com/#!/)
Se nenhuma das duas coisas funcionar, por favor me avisa aqui porque aí preciso investigar mais a fundo o problema.

**Comment by idmarjr** [comment]
Como faz um mês desde meu último comentário e não recebi resposta, estou considerando essa _issue_ como resolvida.  
Lembrando que a gente sempre pode reabri-lá se necessário.
