### ISSUE TITLE
Importar modelos da versão offline

### ISSUE THREAD

**Issue by LeMorelli-py** [miltonbsn/brmodelo#499]
### Sua sugestão de melhoria é relacionada a algum problema?

Eu estava fazendo um modelo conceitual para um trabalho da faculdade e quis testar o online para ver se estava melhor,
mas não consigo importar o que está no meu computador e continuar o trabalho

---

### Descreva sua ideia de como resolver o problema

N/A

---

### Informações extras

N/A

**Comment by idmarjr** [comment]
Oi @LeMorelli-py 

Obrigado pela sua sugestão.
Nesse comentário eu explico um pouco melhor do porque não é possível importar modelos do app desktop:
https://github.com/brmodeloweb/brmodelo-app/issues/416#issuecomment-1504079346

Nós temos a inteção de implementar essa feature um dia mas isso é um pouco mais complicado do que parece para ser implementado por questões de segurança.  

Por hora, infelizmente isso não está na lista de prioridades 😢 

## Related to
#76, #176, #413, #416 , #432, #442

**Comment by LeMorelli-py** [comment]
Faz sentido, não tinha pensado por esse lado. Muito obrigado...muito sucesso pra vc

**Comment by idmarjr** [comment]
Como não temos previsão de implementar essa feature, vou encerrar essa issue.  
Mas mais uma vez, obrigado pela sugestão! 😄
