### ISSUE TITLE
Logical model

### ISSUE THREAD

**Issue by 7Francisco** [miltonbsn/brmodelo#501]
I am not being able to add the keys and the other attributes to the Entity in the Logical model.

**Comment by idmarjr** [comment]
Oi @7Francisco 

Você pode por favor mandar o link do modelo que você está enfrentando esse problema?
Se possível compartilhar screenshots da tela, também nos ajuda a entender o problema pra podermos investigar melhor.

**Comment by idmarjr** [comment]
Como não recebemos mais detalhes pra poder investigar o problema, vou encerrar essa issue por hora.
Lembrando que sempre podemos reabri-la no futuro
