### ISSUE TITLE
o espaco de trabalho nao amplia

### ISSUE THREAD

**Issue by RodaTadeu** [miltonbsn/brmodelo#503]
### Link da modelagem

https://app.brmodeloweb.com/#!/conceptual/65e30318233920173711a171

---

### Descreva o problema
Adicione aqui uma breve descrição do problema.

---

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by RodaTadeu** [comment]
https://app.brmodeloweb.com/#!/conceptual/65e30318233920173711a171

**Comment by RodaTadeu** [comment]
https://app.brmodeloweb.com/#!/conceptual/65e30318233920173711a171
link da modelagem q estou trabalhando

**Comment by idmarjr** [comment]
Oi @RodaTadeu 

Você pode dar mais dealhes. Não tá claro pra mim o que tu quer dizer com _"o espaco de trabalho nao amplia"_.

Que ações você tá fazendo ou tentando fazer?  
Se você puder compartilhar um ou mais screnshots demonstrando o problema, ajuda bastante a entendermos o que está acontecendo. 😄

**Comment by RodaTadeu** [comment]
Oops !!! Ja encontrei o meu erro!!
Obrigado de qq maneira
