### ISSUE TITLE
subir a modelagem

### ISSUE THREAD

**Issue by Tgrauth** [miltonbsn/brmodelo#505]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Adicione aqui sua pergunta

**Comment by idmarjr** [comment]
@Tgrauth 
Você pode dar mais detalhes, por favor? :) 

O que você quer dizer exatamente com "subir modelo"?

**Comment by idmarjr** [comment]
Como não recebemos mais detalhes pra poder investigar o problema, vou fechar essa issue.
Lembrando que sempre podemos reabri-la nop futuro. :)
