### ISSUE TITLE
nao consigo colocar a entidade associativa 

### ISSUE THREAD

**Issue by VitoriaVirgini** [miltonbsn/brmodelo#506]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Adicione aqui sua pergunta

**Comment by idmarjr** [comment]
Oi @VitoriaVirgini 
Você pode por favor compartilhar o link do modelo pra que a gente possa investigar mais a fundo o problema?

**Comment by idmarjr** [comment]
Como não tivemos mais detalhes do problema em quase 30 dias, vou encerrar a issue.
Lembrando que sempre podemos reabri-la se necessário.
