### ISSUE TITLE
FALTA DE FLUIDEZ PARA O USUÁRIO COMUM

### ISSUE THREAD

**Issue by victoriaflb** [miltonbsn/brmodelo#508]
### Descreva o problema
Falta de fluidez para o usuário comum

### Sistema operacional e navegador
 - Windows 10
 - Brave

---

### Informações extras
Muito ruim para um usuário comum

**Comment by idmarjr** [comment]
Oi @victoriaflb !

Você pode me dar mais informações? O que exatamente você quer dizer com "falta de fluidez"?

**Comment by idmarjr** [comment]
Estou fechando essa issue devido à falta de informações.
Lembrando que sempre podemos reabri-la se necessário.
