### ISSUE TITLE
depois de um tempo de uso, ele trava e é necessário salvar e recarregar a página

### ISSUE THREAD

**Issue by LauraRMota** [miltonbsn/brmodelo#510]
### Link da modelagem
Adicione aqui o link da modelagem na qual você estava trabalhando quando encontrou o problema.

---

### Descreva o problema
Adicione aqui uma breve descrição do problema.

---

### Passos para reproduzir
1. Na tela de...
1. Selecione a opção...
1. Clique em...

---

### Screenshots e/ou video
Adicione aqui imagens ou videos que possam nos ajudar a entender o problema

---

### Sistema operacional e navegador
 - Adicione aqui seu sistema operacional (Windows, MacOS, Linux distro, etc...)
 - Adicione aqui seu navegador (Firefox, Chrome, Edge, etc) e a versão do mesmo

---

### Informações extras
Aqui você pode adicionar qualquer informação extra que ache relevante pra nos ajudar a entender o problema.

**Comment by idmarjr** [comment]
@LauraRMota esse problema está acontecendo em mais de uma modelagem?

Você pode por favor compartilhar o link do(s) modelo(s) nos quais você tá tendo esse problema tá wye a gente possa investigar mais a fundo?

**Comment by idmarjr** [comment]
Como não tivemos mais informações pra poder investigar o problema, vou encerrar essa issue .
Lembrando que sempre podemos reabri-la se necessário. 😄
