### ISSUE TITLE
Logar com outras contas

### ISSUE THREAD

**Issue by natanoliveira** [miltonbsn/brmodelo#523]
Bom dia. Acredito que seria muito eficiente colocar o login por contas exemplo: Google, Github, LinkedIn, Outlook e etc.

**Comment by idmarjr** [comment]
Oi @natanoliveira !
Obrigado pela sugestão :)
Já existe uma issue relacionada a isso ( #103  ) porém ela tem prioridade baixa no nosso backlog.

Se você tiver disponibilidade e quiser abrir um pull request propondo uma implementação disso, manda a ver que a gente analisa.

Pra evitar duplicadas, vou encerrar essa issue e a gente pode continuar essa conversa na #103 :)
