### ISSUE TITLE
Confirmação de email para criação de conta

### ISSUE THREAD

**Issue by GM7Avila** [miltonbsn/brmodelo#539]
Seria mais adequado se durante o cadastro da conta, fosse necessário verificar se o endereço de e-mail informado é realmente do ator em questão.

Poderia ser o envio de um e-mail para o usuário - assim como nas maiorias dos sites atuais - onde o usuário receberia em sua caixa postal, as instruções para confirmar o seu cadastro.

**Comment by miltonbsn** [comment]
Opa @GM7Avila beleza? A ideia é boa, mas fica um pouco caro pra gente mandar esses emails. Hoje todos os recursos de infra nós quem financiamos (do próprio salário). Talvez no futuro eu implemente um login integrado com google etc. De qualquer jeito, obrigado pela sugestão
