### ISSUE TITLE
BR MODELO HORRÍVEL!!!!

### ISSUE THREAD

**Issue by mariasteckert** [miltonbsn/brmodelo#553]
SITE MUITO RUIM, TRAVA TODO E NÃO DEIXA NADA RETO. PARECE QUE FAZ SÓ PARA IRRITAR. ESTOU TENTANDO FAZER O MEU TCC MAS ESTÁ SIMPLESMENTE IMPOSSÍVEL!!!
PARABÉNS BR MODELO, MENOS UM USUÁRIO, VOU FALAR MAL DESSE SITE PRA TODO MUNDO QUE EU CONHEÇO.

**Comment by mariasteckert** [comment]
SITE MUITO RUIM, FAÇAM ALGUMA COISA IMEDIATAMENTE

**Comment by mariasteckert** [comment]
QUE PROJETOU ESSE SITE NÃO USOU UM DIAGRAMA DE ENTIDADE E RELACIONAMENTO POIS ELE É HORRÍVEL

**Comment by miltonbsn** [comment]
@merdacombr criou email falso por que?
